version: "3.7"
services:
  db:
    build: development/db
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=pw4postgres"
      - "DB_APP_NAME=snafu-todss"
      - "DB_APP_USER=snafu-todss-user"
      - "DB_APP_PASS=snafu-todss-user-password"
    volumes:
      - "./development/data:/var/data/db"
